// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           int64
	PrincipalID  pgtype.UUID
	ClientID     pgtype.UUID
	Action       string
	ResourceType string
	ResourceID   pgtype.UUID
	Result       string
	RequestID    pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type Checkpoint struct {
	ID                 pgtype.UUID
	TaskID             pgtype.UUID
	TaskVersion        int64
	Kind               string
	Summary            string
	Completed          []string
	Remaining          []string
	Warnings           []string
	ChangedPaths       []string
	TestResults        []string
	SourceRevision     pgtype.Text
	CreatedByPrincipal pgtype.UUID
	CreatedByClient    pgtype.UUID
	IdempotencyKey     string
	RequestDigest      []byte
	CreatedAt          pgtype.Timestamptz
}

type ClientToken struct {
	ID           pgtype.UUID
	PrincipalID  pgtype.UUID
	DisplayName  string
	SecretDigest []byte
	Scopes       []string
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

type ClientTokenSpace struct {
	TokenID pgtype.UUID
	SpaceID pgtype.UUID
}

type Principal struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type PrincipalSpace struct {
	PrincipalID pgtype.UUID
	SpaceID     pgtype.UUID
}

type Project struct {
	ID                  pgtype.UUID
	SpaceID             pgtype.UUID
	Name                string
	Description         string
	RepositoryReference pgtype.Text
	SyncPolicy          string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Space struct {
	ID                pgtype.UUID
	Name              string
	DefaultSyncPolicy string
	CreatedAt         pgtype.Timestamptz
}

type Task struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Title        string
	Objective    string
	Status       string
	Version      int64
	BaseRevision pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
