// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (space_id, name, description, repository_reference, sync_policy)
VALUES ($1::uuid, $2, $3, $4, $5)
RETURNING id::text AS id, space_id::text AS space_id, name, description,
    repository_reference, sync_policy, created_at, updated_at
`

type CreateProjectParams struct {
	SpaceID             pgtype.UUID
	Name                string
	Description         string
	RepositoryReference pgtype.Text
	SyncPolicy          string
}

type CreateProjectRow struct {
	ID                  string
	SpaceID             string
	Name                string
	Description         string
	RepositoryReference pgtype.Text
	SyncPolicy          string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.SpaceID,
		arg.Name,
		arg.Description,
		arg.RepositoryReference,
		arg.SyncPolicy,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Description,
		&i.RepositoryReference,
		&i.SyncPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, objective, status, base_revision)
VALUES ($1::uuid, $2, $3, 'todo', $4)
RETURNING id::text AS id, project_id::text AS project_id, title, objective,
    status, version, base_revision, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID    pgtype.UUID
	Title        string
	Objective    string
	BaseRevision pgtype.Text
}

type CreateTaskRow struct {
	ID           string
	ProjectID    string
	Title        string
	Objective    string
	Status       string
	Version      int64
	BaseRevision pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Objective,
		arg.BaseRevision,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Objective,
		&i.Status,
		&i.Version,
		&i.BaseRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSpace = `-- name: GetProjectSpace :one
SELECT space_id::text AS space_id, sync_policy
FROM projects WHERE id = $1::uuid
`

type GetProjectSpaceRow struct {
	SpaceID    string
	SyncPolicy string
}

func (q *Queries) GetProjectSpace(ctx context.Context, projectID pgtype.UUID) (GetProjectSpaceRow, error) {
	row := q.db.QueryRow(ctx, getProjectSpace, projectID)
	var i GetProjectSpaceRow
	err := row.Scan(&i.SpaceID, &i.SyncPolicy)
	return i, err
}

const getTaskSpace = `-- name: GetTaskSpace :one
SELECT p.space_id::text AS space_id, p.sync_policy
FROM tasks t JOIN projects p ON p.id = t.project_id
WHERE t.id = $1::uuid
`

type GetTaskSpaceRow struct {
	SpaceID    string
	SyncPolicy string
}

func (q *Queries) GetTaskSpace(ctx context.Context, taskID pgtype.UUID) (GetTaskSpaceRow, error) {
	row := q.db.QueryRow(ctx, getTaskSpace, taskID)
	var i GetTaskSpaceRow
	err := row.Scan(&i.SpaceID, &i.SyncPolicy)
	return i, err
}

const getTokenByDigest = `-- name: GetTokenByDigest :one
SELECT id::text AS id, principal_id::text AS principal_id, scopes
FROM client_tokens
WHERE secret_digest = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

type GetTokenByDigestRow struct {
	ID          string
	PrincipalID string
	Scopes      []string
}

func (q *Queries) GetTokenByDigest(ctx context.Context, secretDigest []byte) (GetTokenByDigestRow, error) {
	row := q.db.QueryRow(ctx, getTokenByDigest, secretDigest)
	var i GetTokenByDigestRow
	err := row.Scan(&i.ID, &i.PrincipalID, &i.Scopes)
	return i, err
}

const getTokenSpaces = `-- name: GetTokenSpaces :many
SELECT s.id::text AS id, s.name
FROM client_token_spaces cts
JOIN client_tokens ct ON ct.id = cts.token_id
JOIN principal_spaces ps ON ps.principal_id = ct.principal_id AND ps.space_id = cts.space_id
JOIN spaces s ON s.id = cts.space_id
WHERE cts.token_id = $1::uuid
ORDER BY s.name
`

type GetTokenSpacesRow struct {
	ID   string
	Name string
}

func (q *Queries) GetTokenSpaces(ctx context.Context, tokenID pgtype.UUID) ([]GetTokenSpacesRow, error) {
	rows, err := q.db.Query(ctx, getTokenSpaces, tokenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTokenSpacesRow{}
	for rows.Next() {
		var i GetTokenSpacesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestHandoff = `-- name: LatestHandoff :one
SELECT id::text AS id, task_id::text AS task_id, task_version, kind, summary,
    completed, remaining, warnings, changed_paths, test_results,
    source_revision, created_by_principal::text AS created_by_principal,
    created_by_client::text AS created_by_client, created_at
FROM checkpoints WHERE task_id = $1::uuid AND kind = 'handoff'
ORDER BY task_version DESC LIMIT 1
`

type LatestHandoffRow struct {
	ID                 string
	TaskID             string
	TaskVersion        int64
	Kind               string
	Summary            string
	Completed          []string
	Remaining          []string
	Warnings           []string
	ChangedPaths       []string
	TestResults        []string
	SourceRevision     pgtype.Text
	CreatedByPrincipal string
	CreatedByClient    string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) LatestHandoff(ctx context.Context, taskID pgtype.UUID) (LatestHandoffRow, error) {
	row := q.db.QueryRow(ctx, latestHandoff, taskID)
	var i LatestHandoffRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TaskVersion,
		&i.Kind,
		&i.Summary,
		&i.Completed,
		&i.Remaining,
		&i.Warnings,
		&i.ChangedPaths,
		&i.TestResults,
		&i.SourceRevision,
		&i.CreatedByPrincipal,
		&i.CreatedByClient,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id::text AS id, project_id::text AS project_id, title, objective,
    status, version, base_revision, created_at, updated_at
FROM tasks WHERE project_id = $1::uuid
ORDER BY created_at DESC, id DESC LIMIT 100
`

type ListTasksRow struct {
	ID           string
	ProjectID    string
	Title        string
	Objective    string
	Status       string
	Version      int64
	BaseRevision pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListTasks(ctx context.Context, projectID pgtype.UUID) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Objective,
			&i.Status,
			&i.Version,
			&i.BaseRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskTimeline = `-- name: TaskTimeline :many
SELECT id::text AS id, task_id::text AS task_id, task_version, kind, summary,
    completed, remaining, warnings, changed_paths, test_results,
    source_revision, created_by_principal::text AS created_by_principal,
    created_by_client::text AS created_by_client, created_at
FROM checkpoints WHERE task_id = $1::uuid
ORDER BY task_version DESC LIMIT 50
`

type TaskTimelineRow struct {
	ID                 string
	TaskID             string
	TaskVersion        int64
	Kind               string
	Summary            string
	Completed          []string
	Remaining          []string
	Warnings           []string
	ChangedPaths       []string
	TestResults        []string
	SourceRevision     pgtype.Text
	CreatedByPrincipal string
	CreatedByClient    string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) TaskTimeline(ctx context.Context, taskID pgtype.UUID) ([]TaskTimelineRow, error) {
	rows, err := q.db.Query(ctx, taskTimeline, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTimelineRow{}
	for rows.Next() {
		var i TaskTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TaskVersion,
			&i.Kind,
			&i.Summary,
			&i.Completed,
			&i.Remaining,
			&i.Warnings,
			&i.ChangedPaths,
			&i.TestResults,
			&i.SourceRevision,
			&i.CreatedByPrincipal,
			&i.CreatedByClient,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchToken = `-- name: TouchToken :exec
UPDATE client_tokens SET last_used_at = now()
WHERE id = $1::uuid
  AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

func (q *Queries) TouchToken(ctx context.Context, tokenID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchToken, tokenID)
	return err
}
